<?php

use console\components\Migration;

class m191129_132407_insert_regions extends Migration {
    private $regions = [
        ['pl'=>'Afganistan', 'en'=>'Afghanistan', 'symbol'=>'af'],
        ['pl'=>'Albania', 'en'=>'Albania', 'symbol'=>'al'],
        ['pl'=>'Algieria', 'en'=>'Algeria', 'symbol'=>'dz'],
        ['pl'=>'Andora', 'en'=>'Andorra', 'symbol'=>'ad'],
        ['pl'=>'Angola', 'en'=>'Angola', 'symbol'=>'ao'],
        ['pl'=>'Antigua i Barbuda', 'en'=>'Antigua and Barbuda', 'symbol'=>'ag'],
        ['pl'=>'Arabia Saudyjska', 'en'=>'Saudi Arabia', 'symbol'=>'sa'],
        ['pl'=>'Argentyna', 'en'=>'Argentina', 'symbol'=>'ar'],
        ['pl'=>'Armenia', 'en'=>'Armenia', 'symbol'=>'am'],
        ['pl'=>'Australia', 'en'=>'Australia', 'symbol'=>'au'],
        ['pl'=>'Austria', 'en'=>'Austria', 'symbol'=>'at'],
        ['pl'=>'Azerbejdżan', 'en'=>'Azerbaijan', 'symbol'=>'az'],
        ['pl'=>'Bahamy', 'en'=>'Bahamas', 'symbol'=>'bs'],
        ['pl'=>'Bahrajn', 'en'=>'Bahrain', 'symbol'=>'bh'],
        ['pl'=>'Bangladesz', 'en'=>'Bangladesh', 'symbol'=>'bd'],
        ['pl'=>'Barbados', 'en'=>'Barbados', 'symbol'=>'bb'],
        ['pl'=>'Belgia', 'en'=>'Belgium', 'symbol'=>'be'],
        ['pl'=>'Belize', 'en'=>'Belize', 'symbol'=>'bz'],
        ['pl'=>'Benin', 'en'=>'Benin', 'symbol'=>'bj'],
        ['pl'=>'Bhutan', 'en'=>'Bhutan', 'symbol'=>'bt'],
        ['pl'=>'Białoruś', 'en'=>'Belarus', 'symbol'=>'by'],
        ['pl'=>'Boliwia', 'en'=>'Bolivia, Plurinational State of', 'symbol'=>'bo'],
        ['pl'=>'Bośnia i Hercegowina', 'en'=>'Bosnia and Herzegovina', 'symbol'=>'ba'],
        ['pl'=>'Botswana', 'en'=>'Botswana', 'symbol'=>'bw'],
        ['pl'=>'Brazylia', 'en'=>'Brazil', 'symbol'=>'br'],
        ['pl'=>'Brunei', 'en'=>'Brunei Darussalam', 'symbol'=>'bn'],
        ['pl'=>'Bułgaria', 'en'=>'Bulgaria', 'symbol'=>'bg'],
        ['pl'=>'Burkina Faso', 'en'=>'Burkina Faso', 'symbol'=>'bf'],
        ['pl'=>'Burundi', 'en'=>'Burundi', 'symbol'=>'bi'],
        ['pl'=>'Chile', 'en'=>'Chile', 'symbol'=>'cl'],
        ['pl'=>'Chiny', 'en'=>'China', 'symbol'=>'cn'],
        ['pl'=>'Chorwacja', 'en'=>'Croatia', 'symbol'=>'hr'],
        ['pl'=>'Cypr', 'en'=>'Cyprus', 'symbol'=>'cy'],
        ['pl'=>'Czad', 'en'=>'Chad', 'symbol'=>'td'],
        ['pl'=>'Czarnogóra', 'en'=>'Montenegro', 'symbol'=>'me'],
        ['pl'=>'Czechy', 'en'=>'Czechia', 'symbol'=>'cz'],
        ['pl'=>'Dania', 'en'=>'Denmark', 'symbol'=>'dk'],
        ['pl'=>'Demokratyczna Republika Konga', 'en'=>'Congo, the Democratic Republic of the', 'symbol'=>'cd'],
        ['pl'=>'Dominika', 'en'=>'Dominica', 'symbol'=>'dm'],
        ['pl'=>'Dominikana', 'en'=>'Dominican Republic', 'symbol'=>'do'],
        ['pl'=>'Dżibuti', 'en'=>'Djibouti', 'symbol'=>'dj'],
        ['pl'=>'Egipt', 'en'=>'Egypt', 'symbol'=>'eg'],
        ['pl'=>'Ekwador', 'en'=>'Ecuador', 'symbol'=>'ec'],
        ['pl'=>'Erytrea', 'en'=>'Eritrea', 'symbol'=>'er'],
        ['pl'=>'Estonia', 'en'=>'Estonia', 'symbol'=>'ee'],
        ['pl'=>'Eswatini', 'en'=>'Eswatini', 'symbol'=>'sz'],
        ['pl'=>'Etiopia', 'en'=>'Ethiopia', 'symbol'=>'et'],
        ['pl'=>'Fidżi', 'en'=>'Fiji', 'symbol'=>'fj'],
        ['pl'=>'Filipiny', 'en'=>'Philippines', 'symbol'=>'ph'],
        ['pl'=>'Finlandia', 'en'=>'Finland', 'symbol'=>'fi'],
        ['pl'=>'Francja', 'en'=>'France', 'symbol'=>'fr'],
        ['pl'=>'Gabon', 'en'=>'Gabon', 'symbol'=>'ga'],
        ['pl'=>'Gambia', 'en'=>'Gambia', 'symbol'=>'gm'],
        ['pl'=>'Ghana', 'en'=>'Ghana', 'symbol'=>'gh'],
        ['pl'=>'Grecja', 'en'=>'Greece', 'symbol'=>'gr'],
        ['pl'=>'Grenada', 'en'=>'Grenada', 'symbol'=>'gd'],
        ['pl'=>'Gruzja', 'en'=>'Georgia', 'symbol'=>'ge'],
        ['pl'=>'Gujana', 'en'=>'Guyana', 'symbol'=>'gy'],
        ['pl'=>'Gwatemala', 'en'=>'Guatemala', 'symbol'=>'gt'],
        ['pl'=>'Gwinea Bissau', 'en'=>'Guinea-Bissau', 'symbol'=>'gw'],
        ['pl'=>'Gwinea Równikowa', 'en'=>'Equatorial Guinea', 'symbol'=>'gq'],
        ['pl'=>'Gwinea', 'en'=>'Guinea', 'symbol'=>'gn'],
        ['pl'=>'Haiti', 'en'=>'Haiti', 'symbol'=>'ht'],
        ['pl'=>'Hiszpania', 'en'=>'Spain', 'symbol'=>'es'],
        ['pl'=>'Holandia', 'en'=>'Netherlands', 'symbol'=>'nl'],
        ['pl'=>'Honduras', 'en'=>'Honduras', 'symbol'=>'hn'],
        ['pl'=>'Indie', 'en'=>'India', 'symbol'=>'in'],
        ['pl'=>'Indonezja', 'en'=>'Indonesia', 'symbol'=>'id'],
        ['pl'=>'Irak', 'en'=>'Iraq', 'symbol'=>'iq'],
        ['pl'=>'Iran', 'en'=>'Iran, Islamic Republic of', 'symbol'=>'ir'],
        ['pl'=>'Irlandia', 'en'=>'Ireland', 'symbol'=>'ie'],
        ['pl'=>'Islandia', 'en'=>'Iceland', 'symbol'=>'is'],
        ['pl'=>'Izrael', 'en'=>'Israel', 'symbol'=>'il'],
        ['pl'=>'Jamajka', 'en'=>'Jamaica', 'symbol'=>'jm'],
        ['pl'=>'Japonia', 'en'=>'Japan', 'symbol'=>'jp'],
        ['pl'=>'Jemen', 'en'=>'Yemen', 'symbol'=>'ye'],
        ['pl'=>'Jordania', 'en'=>'Jordan', 'symbol'=>'jo'],
        ['pl'=>'Kambodża', 'en'=>'Cambodia', 'symbol'=>'kh'],
        ['pl'=>'Kamerun', 'en'=>'Cameroon', 'symbol'=>'cm'],
        ['pl'=>'Kanada', 'en'=>'Canada', 'symbol'=>'ca'],
        ['pl'=>'Katar', 'en'=>'Qatar', 'symbol'=>'qa'],
        ['pl'=>'Kazachstan', 'en'=>'Kazakhstan', 'symbol'=>'kz'],
        ['pl'=>'Kenia', 'en'=>'Kenya', 'symbol'=>'ke'],
        ['pl'=>'Kirgistan', 'en'=>'Kyrgyzstan', 'symbol'=>'kg'],
        ['pl'=>'Kiribati', 'en'=>'Kiribati', 'symbol'=>'ki'],
        ['pl'=>'Kolumbia', 'en'=>'Colombia', 'symbol'=>'co'],
        ['pl'=>'Komory', 'en'=>'Comoros', 'symbol'=>'km'],
        ['pl'=>'Kongo', 'en'=>'Congo', 'symbol'=>'cg'],
        ['pl'=>'Korea Południowa', 'en'=>'Korea, Republic of', 'symbol'=>'kr'],
        ['pl'=>'Korea Północna', 'en'=>'Korea, Democratic People’s Republic of', 'symbol'=>'kp'],
        ['pl'=>'Kostaryka', 'en'=>'Costa Rica', 'symbol'=>'cr'],
        ['pl'=>'Kuba', 'en'=>'Cuba', 'symbol'=>'cu'],
        ['pl'=>'Kuwejt', 'en'=>'Kuwait', 'symbol'=>'kw'],
        ['pl'=>'Laos', 'en'=>'Lao People’s Democratic Republic', 'symbol'=>'la'],
        ['pl'=>'Lesotho', 'en'=>'Lesotho', 'symbol'=>'ls'],
        ['pl'=>'Liban', 'en'=>'Lebanon', 'symbol'=>'lb'],
        ['pl'=>'Liberia', 'en'=>'Liberia', 'symbol'=>'lr'],
        ['pl'=>'Libia', 'en'=>'Libyan Arab Jamahiriya', 'symbol'=>'ly'],
        ['pl'=>'Liechtenstein', 'en'=>'Liechtenstein', 'symbol'=>'li'],
        ['pl'=>'Litwa', 'en'=>'Lithuania', 'symbol'=>'lt'],
        ['pl'=>'Luksemburg', 'en'=>'Luxembourg', 'symbol'=>'lu'],
        ['pl'=>'Łotwa', 'en'=>'Latvia', 'symbol'=>'lv'],
        ['pl'=>'Macedonia Północna', 'en'=>'tekst=Macedonia, the former Yugoslav Republic of', 'symbol'=>'mk'],
        ['pl'=>'Madagaskar', 'en'=>'Madagascar', 'symbol'=>'mg'],
        ['pl'=>'Malawi', 'en'=>'Malawi', 'symbol'=>'mw'],
        ['pl'=>'Malediwy', 'en'=>'Maldives', 'symbol'=>'mv'],
        ['pl'=>'Malezja', 'en'=>'Malaysia', 'symbol'=>'my'],
        ['pl'=>'Mali', 'en'=>'Mali', 'symbol'=>'ml'],
        ['pl'=>'Malta', 'en'=>'Malta', 'symbol'=>'mt'],
        ['pl'=>'Maroko', 'en'=>'Morocco', 'symbol'=>'ma'],
        ['pl'=>'Mauretania', 'en'=>'Mauritania', 'symbol'=>'mr'],
        ['pl'=>'Mauritius', 'en'=>'Mauritius', 'symbol'=>'mu'],
        ['pl'=>'Meksyk', 'en'=>'Mexico', 'symbol'=>'mx'],
        ['pl'=>'Mikronezja', 'en'=>'Micronesia, Federated States of', 'symbol'=>'fm'],
        ['pl'=>'Mjanma', 'en'=>'Myanmar', 'symbol'=>'mm'],
        ['pl'=>'Mołdawia', 'en'=>'Moldova, Republic of', 'symbol'=>'md'],
        ['pl'=>'Monako', 'en'=>'Monaco', 'symbol'=>'mc'],
        ['pl'=>'Mongolia', 'en'=>'Mongolia', 'symbol'=>'mn'],
        ['pl'=>'Mozambik', 'en'=>'Mozambique', 'symbol'=>'mz'],
        ['pl'=>'Namibia', 'en'=>'Namibia', 'symbol'=>'na'],
        ['pl'=>'Nauru', 'en'=>'Nauru', 'symbol'=>'nr'],
        ['pl'=>'Nepal', 'en'=>'Nepal', 'symbol'=>'np'],
        ['pl'=>'Niemcy', 'en'=>'Germany', 'symbol'=>'de'],
        ['pl'=>'Niger', 'en'=>'Niger', 'symbol'=>'ne'],
        ['pl'=>'Nigeria', 'en'=>'Nigeria', 'symbol'=>'ng'],
        ['pl'=>'Nikaragua', 'en'=>'Nicaragua', 'symbol'=>'ni'],
        ['pl'=>'Norwegia', 'en'=>'Norway', 'symbol'=>'no'],
        ['pl'=>'Nowa Kaledonia', 'en'=>'New Caledonia', 'symbol'=>'nc'],
        ['pl'=>'Nowa Zelandia', 'en'=>'New Zealand', 'symbol'=>'nz'],
        ['pl'=>'Oman', 'en'=>'Oman', 'symbol'=>'om'],
        ['pl'=>'Pakistan', 'en'=>'Pakistan', 'symbol'=>'pk'],
        ['pl'=>'Palau', 'en'=>'Palau', 'symbol'=>'pw'],
        ['pl'=>'Panama', 'en'=>'Panama', 'symbol'=>'pa'],
        ['pl'=>'Papua-Nowa Gwinea', 'en'=>'Papua New Guinea', 'symbol'=>'pg'],
        ['pl'=>'Paragwaj', 'en'=>'Paraguay', 'symbol'=>'py'],
        ['pl'=>'Peru', 'en'=>'Peru', 'symbol'=>'pe'],
        ['pl'=>'Portugalia', 'en'=>'Portugal', 'symbol'=>'pt'],
        ['pl'=>'Republika Południowej Afryki', 'en'=>'South Africa', 'symbol'=>'za'],
        ['pl'=>'Republika Środkowoafrykańska', 'en'=>'Central African Republic', 'symbol'=>'cf'],
        ['pl'=>'Republika Zielonego Przylądka', 'en'=>'Cape Verde', 'symbol'=>'cv'],
        ['pl'=>'Rosja', 'en'=>'Russian Federation', 'symbol'=>'ru'],
        ['pl'=>'Rumunia', 'en'=>'Romania', 'symbol'=>'ro'],
        ['pl'=>'Rwanda', 'en'=>'Rwanda', 'symbol'=>'rw'],
        ['pl'=>'Saint Kitts i Nevis', 'en'=>'Saint Kitts and Nevis', 'symbol'=>'kn'],
        ['pl'=>'Saint Lucia', 'en'=>'Saint Lucia', 'symbol'=>'lc'],
        ['pl'=>'Saint Vincent i Grenadyny', 'en'=>'Saint Vincent and the Grenadines', 'symbol'=>'vc'],
        ['pl'=>'Salwador', 'en'=>'El Salvador', 'symbol'=>'sv'],
        ['pl'=>'Samoa', 'en'=>'Samoa', 'symbol'=>'ws'],
        ['pl'=>'San Marino', 'en'=>'San Marino', 'symbol'=>'sm'],
        ['pl'=>'Senegal', 'en'=>'Senegal', 'symbol'=>'sn'],
        ['pl'=>'Serbia', 'en'=>'Serbia', 'symbol'=>'rs'],
        ['pl'=>'Seszele', 'en'=>'Seychelles', 'symbol'=>'sc'],
        ['pl'=>'Sierra Leone', 'en'=>'Sierra Leone', 'symbol'=>'sl'],
        ['pl'=>'Singapur', 'en'=>'Singapore', 'symbol'=>'sg'],
        ['pl'=>'Słowacja', 'en'=>'Slovakia', 'symbol'=>'sk'],
        ['pl'=>'Słowenia', 'en'=>'Slovenia', 'symbol'=>'si'],
        ['pl'=>'Somalia', 'en'=>'Somalia', 'symbol'=>'so'],
        ['pl'=>'Sri Lanka', 'en'=>'Sri Lanka', 'symbol'=>'lk'],
        ['pl'=>'Stany Zjednoczone', 'en'=>'United States', 'symbol'=>'us'],
        ['pl'=>'Sudan', 'en'=>'Sudan', 'symbol'=>'sd'],
        ['pl'=>'Sudan Południowy', 'en'=>'South Sudan', 'symbol'=>'ss'],
        ['pl'=>'Surinam', 'en'=>'Suriname', 'symbol'=>'sr'],
        ['pl'=>'Syria', 'en'=>'Syrian Arab Republic', 'symbol'=>'sy'],
        ['pl'=>'Szwajcaria', 'en'=>'Switzerland', 'symbol'=>'ch'],
        ['pl'=>'Szwecja', 'en'=>'Sweden', 'symbol'=>'se'],
        ['pl'=>'Tadżykistan', 'en'=>'Tajikistan', 'symbol'=>'tj'],
        ['pl'=>'Tajlandia', 'en'=>'Thailand', 'symbol'=>'th'],
        ['pl'=>'Tanzania', 'en'=>'Tanzania, United Republic of', 'symbol'=>'tz'],
        ['pl'=>'Timor Wschodni', 'en'=>'Timor-Leste', 'symbol'=>'tl'],
        ['pl'=>'Togo', 'en'=>'Togo', 'symbol'=>'tg'],
        ['pl'=>'Tonga', 'en'=>'Tonga', 'symbol'=>'to'],
        ['pl'=>'Trynidad i Tobago', 'en'=>'Trinidad and Tobago', 'symbol'=>'tt'],
        ['pl'=>'Tunezja', 'en'=>'Tunisia', 'symbol'=>'tn'],
        ['pl'=>'Turcja', 'en'=>'Turkey', 'symbol'=>'tr'],
        ['pl'=>'Turkmenistan', 'en'=>'Turkmenistan', 'symbol'=>'tm'],
        ['pl'=>'Turks i Caicos', 'en'=>'Turks and Caicos Islands', 'symbol'=>'tc'],
        ['pl'=>'Tuvalu', 'en'=>'Tuvalu', 'symbol'=>'tv'],
        ['pl'=>'Uganda', 'en'=>'Uganda', 'symbol'=>'ug'],
        ['pl'=>'Ukraina', 'en'=>'Ukraine', 'symbol'=>'ua'],
        ['pl'=>'Urugwaj', 'en'=>'Uruguay', 'symbol'=>'uy'],
        ['pl'=>'Uzbekistan', 'en'=>'Uzbekistan', 'symbol'=>'uz'],
        ['pl'=>'Vanuatu', 'en'=>'Vanuatu', 'symbol'=>'vu'],
        ['pl'=>'Watykan', 'en'=>'Holy See (Vatican City State)', 'symbol'=>'va'],
        ['pl'=>'Wenezuela', 'en'=>'Venezuela, Bolivarian Republic of', 'symbol'=>'ve'],
        ['pl'=>'Węgry', 'en'=>'Hungary', 'symbol'=>'hu'],
        ['pl'=>'Wielka Brytania', 'en'=>'United Kingdom', 'symbol'=>'gb'],
        ['pl'=>'Wietnam', 'en'=>'Viet Nam', 'symbol'=>'vn'],
        ['pl'=>'Włochy', 'en'=>'Italy', 'symbol'=>'it'],
        ['pl'=>'Wybrzeże Kości Słoniowej', 'en'=>'Côte d’Ivoire', 'symbol'=>'ci'],
        ['pl'=>'Wyspy Marshalla', 'en'=>'Marshall Islands', 'symbol'=>'mh'],
        ['pl'=>'Wyspy Salomona', 'en'=>'Solomon Islands', 'symbol'=>'sb'],
        ['pl'=>'Wyspy Świętego Tomasza i Książęca', 'en'=>'Sao Tome and Principe', 'symbol'=>'st'],
        ['pl'=>'Zambia', 'en'=>'Zambia', 'symbol'=>'zm'],
        ['pl'=>'Zimbabwe', 'en'=>'Zimbabwe', 'symbol'=>'zw'],
        ['pl'=>'Zjednoczone Emiraty Arabskie', 'en'=>'United Arab Emirates', 'symbol'=>'ae'],
    ];

    public function safeUp() {
        $languages = \common\models\ar\Language::find()->all();
        foreach($this->regions as $region) {
            $this->insert('region', ['symbol' => $region['symbol']]);
            $regionId = $this->db->lastInsertID;
            foreach($languages as $language) {
                $this->insert('region_translation', [
                    'region_id' => $regionId,
                    'language_id' => $language['id'],
                    'name' => $region[$language['symbol']]
                ]);
            }
        }

    }

    public function safeDown() {
        
    }
}
