<?php

use console\components\Migration;
use yii\db\Query;

class m200217_081351_add_agreements_translations extends Migration {

    public function safeUp() {
        $languagePlId = (new Query)->select('id')->from('language')->where(['symbol' => 'pl']);
        $languageEnId = (new Query)->select('id')->from('language')->where(['symbol' => 'en']);

        $termsOfUseId = (new Query)->select('id')->from('agreement')->where(['symbol' => 'terms-of-use']);
        $personalDataProcessingId = (new Query)->select('id')->from('agreement')->where(['symbol' => 'personal-data-processing']);

        $this->insert('agreement_translation', [
            'agreement_id' => $termsOfUseId,
            'language_id' => $languagePlId,
            'content' => '<p><strong><span data-contrast="auto">REGULAMIN KORZYSTANIA Z APLIKACJI POWSTAŁEJ W PROJEKCIE NAWA PT. &bdquo;POZOSTAŃ W KONTAKCIE Z ABSOLWENTAMI PP, STAY CONNECTED WITH PUT ALUMNI&rdquo;</span></strong><span data-ccp-props="{&quot;335551550&quot;:2,&quot;335551620&quot;:2}">&nbsp;</span></p>
<p><span data-ccp-props="{&quot;335551550&quot;:2,&quot;335551620&quot;:2}">&nbsp;</span><strong><span data-contrast="auto">&sect;1&nbsp;</span></strong><strong><span data-contrast="auto">POSTANOWIENIA OG&Oacute;LNE</span></strong><span data-ccp-props="{&quot;335551550&quot;:2,&quot;335551620&quot;:2}">&nbsp;</span></p>
<p><span data-ccp-props="{&quot;335551550&quot;:2,&quot;335551620&quot;:2}">&nbsp;</span></p>
<ol>
<li><span data-contrast="auto"> Niniejszy regulamin (&bdquo;Regulamin&rdquo;) określa zasady korzystania z aplikacji powstałej</span><br /><span data-contrast="auto">w projekcie&nbsp;</span><span data-contrast="auto">NAWA</span><span data-contrast="auto">&nbsp;pt. &bdquo;</span><span data-contrast="auto">P</span><span data-contrast="auto">ozostań w kontakcie z absolwentami&nbsp;</span><span data-contrast="auto">PP</span><span data-contrast="auto">,&nbsp;</span><span data-contrast="auto">S</span><span data-contrast="auto">tay&nbsp;connected&nbsp;with&nbsp;</span><span data-contrast="auto">PUT</span><span data-contrast="auto">&nbsp;</span><span data-contrast="auto">A</span><span data-contrast="auto">lumni&rdquo; mającej na celu integrację środowiska absolwent&oacute;w&nbsp;</span><span data-contrast="auto">P</span><span data-contrast="auto">olitechniki&nbsp;</span><span data-contrast="auto">P</span><span data-contrast="auto">oznańskiej oraz zawiera postanowienia dotyczące polityki prywatności.&nbsp;</span><span data-contrast="auto">A</span><span data-contrast="auto">plikacj</span><span data-contrast="auto">a powstała</span><span data-contrast="auto">&nbsp;w projekcie&nbsp;</span><span data-contrast="auto">NAWA</span><span data-contrast="auto">&nbsp;pt. &bdquo;</span><span data-contrast="auto">P</span><span data-contrast="auto">ozostań w kontakcie z absolwentami&nbsp;</span><span data-contrast="auto">PP</span><span data-contrast="auto">,&nbsp;</span><span data-contrast="auto">S</span><span data-contrast="auto">tay&nbsp;connected&nbsp;with&nbsp;</span><span data-contrast="auto">PUT</span><span data-contrast="auto">&nbsp;</span><span data-contrast="auto">A</span><span data-contrast="auto">lumni&rdquo; będ</span><span data-contrast="auto">zie</span><span data-contrast="auto">&nbsp;zwan</span><span data-contrast="auto">a</span><span data-contrast="auto">&nbsp;dalej &bdquo;Aplikacją&rdquo;.</span><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6}">&nbsp;</span></li>
<li><span data-contrast="auto"> Przed pobraniem i zainstalowaniem Aplikacji, Uczestnik zobowiązany jest do zapoznania się z treścią niniejszego Regulaminu.</span></li>
<li><span data-contrast="auto"> Aplikacja jest administrowana przez jej właściciela, tj.:</span><span data-contrast="auto">Politechnika Poznańska z siedzibą Pl. Marii Skłodowskiej &ndash; Curie 5, e-mail: biuro.rektora@put.poznan.pl, telefon: 61 665 3639</span><span data-contrast="auto">(&bdquo;Administrator&rdquo;).</span><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6}">&nbsp;</span></li>
<li><span data-contrast="auto"> Aplikacja to oprogramowanie działające na urządzeniach przenośnych posiadających dostęp do Internetu i pracujących w oparciu o system operacyjny Android, iOS lub Windows, takich jak np. telefony kom&oacute;rkowe, smartfony, palmtopy, czy tablety, spełniające minimalne wymagania sprzętowe, wskazane w &sect; 2 ust. 4 Regulaminu.</span></li>
</ol>
<p><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6}">&nbsp;<strong><span data-contrast="auto">&sect;</span></strong></span><strong><span data-contrast="auto">2&nbsp;</span></strong><strong><span data-contrast="auto">WARUNKI KORZYSTANIA Z APLIKACJI</span></strong><span data-ccp-props="{&quot;335551550&quot;:2,&quot;335551620&quot;:2}">&nbsp;</span></p>
<p><span data-ccp-props="{&quot;335551550&quot;:2,&quot;335551620&quot;:2}">&nbsp;</span></p>
<ol>
<li><span data-contrast="auto"> Z Aplikacji mogą korzystać pełnoletnie osoby fizyczne, będące</span><span data-contrast="auto">absolwentami Politechniki Poznańskiej.</span></li>
<li><span data-contrast="auto"> Użytkownik może pobrać Aplikację na swoje urządzenie mobilne w dowolnej chwili.</span><br /><span data-contrast="auto">Po pobraniu Aplikacji, Użytkownik może ją zainstalować na swoim urządzeniu przenośnym. Za pobranie Aplikacji lub jej zainstalowanie nie są pobierane opłaty.</span><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6}">&nbsp;</span></li>
<li><span data-contrast="auto"> W celu pobrania, zainstalowania oraz k</span><span data-contrast="auto">orzystania z Aplikacji</span><span data-contrast="auto">Użytkownik powinien posiadać dostęp do Internetu. Aplikację można pobrać, odpowiednio dla system&oacute;w operacyjnych urządzeń mobilnych, ze sklep&oacute;w Google Play, iTunes, WindowsStore&nbsp;przez wyszukanie nazwy Aplikacji, kt&oacute;rą</span><span data-contrast="auto">&nbsp;Użytkownik jest zainteresowany</span><span data-contrast="auto">&rdquo;.</span><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6}">&nbsp;</span></li>
<li><span data-contrast="auto"> Minimalne wymagania sprzętowe i rodzaje urządzeń przenośnych dostosowane</span><br /><span data-contrast="auto">do Aplikacji są następujące:</span><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6}">&nbsp;</span></li>
<li><span data-contrast="auto">a) Aplikację można pobrać na urządzenia przenośne posiadające dostęp do Internetu</span><br /><span data-contrast="auto">i pracujące w oparciu o systemy operacyjne: Android, iOS lub Windows, takie jak np. telefony kom&oacute;rkowe, smartfony, palmtopy, czy tablety;</span><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6}">&nbsp;</span></li>
<li><span data-contrast="auto">b) Minimalne wymagania w zakresie dostępu do sieci Internet, to przepustowość łącza Internetowego 2Mbit/s;</span></li>
<li><span data-contrast="auto">c) Minimalne wymagania w zakresie systemu operacyjnego, to Android wersja 4.2 API 17, iOS 9.0, Windows 10Build</span><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6}">&nbsp;</span></li>
<li><span data-contrast="auto"> Administrator może publikować aktualizacje Aplikacji. Do prawidłowego działania Aplikacji oraz korzystania ze wszystkich jej funkcji, niezbędne jest regularne aktualizowanie Aplikacji. Zmianę polegającą na aktualizacji Aplikacji uważa się zaakceptowaną nie p&oacute;źniej niż w chwili pobrania tej aktualizacji na urządzenie przenośne Użytkownika.</span></li>
</ol>
<p><span data-ccp-props="{&quot;335551550&quot;:2,&quot;335551620&quot;:2}">&nbsp;<span data-contrast="auto"><strong>&sect;</strong></span><strong><span data-contrast="auto">3&nbsp;</span></strong><strong><span data-contrast="auto">FUNCJONALNOŚCI APLIKACJI</span></strong><span data-ccp-props="{&quot;335551550&quot;:2,&quot;335551620&quot;:2}">&nbsp;</span></span></p>
<ol>
<li><span data-contrast="auto"> Po pobraniu i zainstalowaniu Aplikacji, Użytkownik może:</span></li>
</ol>
<ul>
<li data-leveltext="-" data-font="Verdana" data-listid="3" data-aria-posinset="0" data-aria-level="1"><span data-contrast="auto">Stworzyć swoje konto,</span><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;335559685&quot;:540,&quot;335559991&quot;:540,&quot;469777462&quot;:[1080,540],&quot;469777927&quot;:[0,0],&quot;469777928&quot;:[0,8]}">&nbsp;</span></li>
<li data-leveltext="-" data-font="Verdana" data-listid="3" data-aria-posinset="0" data-aria-level="1"><span data-contrast="auto">Modyfikować dane zapisane na koncie,</span><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;335559685&quot;:540,&quot;335559991&quot;:540,&quot;469777462&quot;:[1080,540],&quot;469777927&quot;:[0,0],&quot;469777928&quot;:[0,8]}">&nbsp;</span></li>
<li data-leveltext="-" data-font="Verdana" data-listid="3" data-aria-posinset="0" data-aria-level="1"><span data-contrast="auto">Tworzyć artykuły, wydarzenia i&nbsp;</span><span data-contrast="auto">grywalizacji.</span><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;335559685&quot;:540,&quot;335559991&quot;:540,&quot;469777462&quot;:[1080,540],&quot;469777927&quot;:[0,0],&quot;469777928&quot;:[0,8]}">&nbsp;</span></li>
</ul>
<ol start="2">
<li><span data-contrast="auto"> Użytkownik w każdej chwili może zaprzestać korzystania z Aplikacji. W celu usunięcia Aplikacji z urządzenia Użytkownik powinien odinstalować Aplikację zgodnie z instrukcją danego urządzenia.</span></li>
</ol>
<p><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6}">&nbsp;<strong>&sect;4</strong></span><strong><span data-contrast="auto">&nbsp;</span></strong><strong><span data-contrast="auto">POSTANOWIENIA KOŃCOWE</span></strong><span data-ccp-props="{&quot;335551550&quot;:2,&quot;335551620&quot;:2}">&nbsp;</span></p>
<ol>
<li><span data-contrast="auto"> Administrator zastrzega sobie prawo do zmiany niniejszego Regulaminu w dowolnym czasie.</span></li>
<li><span data-contrast="auto"> Administrator może w każdym czasie wycofać dostęp Aplikacji lub jej poszczeg&oacute;lnych funkcjonalności.&nbsp;</span></li>
<li><span data-contrast="auto"> W sprawach nieuregulowanych w niniejszym Regulaminie zastosowanie mają powszechnie obowiązujące w Polsce przepisy prawa.</span></li>
<li><span data-contrast="auto"> Wszelkie reklamacje dotyczące funkcjonowania Aplikacji będą rozpatrywane w terminie 14 dni od daty ich zgłoszenia.</span></li>
</ol>',
        ]);

        $this->insert('agreement_translation', [
            'agreement_id' => $termsOfUseId,
            'language_id' => $languageEnId,
            'content' => '<p><strong><span data-contrast="auto">TERMS AND CONDITIONS FOR USING THE APPLICATION CREATED IN THE&nbsp;</span></strong><strong><span data-contrast="auto">NAWA PROJECT PT. "STAY CONTACT WITH PP GRADUATES, STAY&nbsp;</span></strong><strong><span data-contrast="auto">CONNECTED WITH PUT ALUMNI"&nbsp;</span></strong><span data-ccp-props="{&quot;335551550&quot;:2,&quot;335551620&quot;:2}">&nbsp;</span></p>
<p><strong><span data-contrast="auto"></span></strong><span data-ccp-props="{&quot;335551550&quot;:2,&quot;335551620&quot;:2}">&nbsp;</span></p>
<p><span data-ccp-props="{&quot;335551550&quot;:2,&quot;335551620&quot;:2}">&nbsp;</span><strong><span data-contrast="auto">&sect;1&nbsp;</span></strong><strong><span data-contrast="auto">GENERAL PROVISIONS</span></strong><span data-ccp-props="{&quot;335551550&quot;:2,&quot;335551620&quot;:2}">&nbsp;</span></p>
<p><span data-ccp-props="{&quot;335551550&quot;:2,&quot;335551620&quot;:2}">&nbsp;</span></p>
<ol>
<li><span data-contrast="auto"> These regulations (the "Regulations") define the rules for using the application created</span><br /><span data-contrast="auto">in the NAWA project entitled "</span><span data-contrast="auto">Pozostań&nbsp;w&nbsp;kontakcie&nbsp;z&nbsp;absolwentami&nbsp;PP</span><span data-contrast="auto">, Stay connected with PUT Alumni" aimed at integrating the environment of graduates of the Poznan University&nbsp;</span>&nbsp;<br /><span data-contrast="auto">of Technology and contains provisions regarding the privacy policy. The application was created in the NAWA project entitled "</span><span data-contrast="auto">Pozostań&nbsp;w&nbsp;kontakcie&nbsp;z&nbsp;absolwentami&nbsp;PP</span><span data-contrast="auto">, Stay connected with PUT Alumni" will be referred to as the "Application".</span><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6}">&nbsp;</span></li>
<li><span data-contrast="auto"> Before downloading and installing the Application, the Participant is required to read</span><br /><span data-contrast="auto">the content of these Regulations.</span><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6}">&nbsp;</span></li>
<li><span data-contrast="auto"> The application is administered by its owner,ie: Poznan University of Technology with the seat of Pl. MariaSkłodowska-Curie 5, e-mail: biuro.rektora@put.poznan.pl, phone: 61 665 3639 ("Administrator").</span><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6}">&nbsp;</span></li>
<li><span data-contrast="auto"> The application is software running on mobile devices with Internet access and operating on the basis of the Android, iOS or Windows operating system, such as e.g. mobile phones, smartphones, palmtops or tablets, which meet the minimum hardwar</span><span data-contrast="auto">e requirements indicated in &sect; 2(</span><span data-contrast="auto">4</span><span data-contrast="auto">)</span><span data-contrast="auto">of the Regulations.</span></li>
</ol>
<p><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6}">&nbsp;</span><strong><span data-contrast="auto">&sect;2&nbsp;</span></strong><strong><span data-contrast="auto">TERMS OF USE OF THE APPLICATION</span></strong><span data-ccp-props="{&quot;335551550&quot;:2,&quot;335551620&quot;:2,&quot;469777462&quot;:[960],&quot;469777927&quot;:[0],&quot;469777928&quot;:[1]}">&nbsp;</span></p>
<p><span data-ccp-props="{&quot;335551550&quot;:2,&quot;335551620&quot;:2,&quot;469777462&quot;:[960],&quot;469777927&quot;:[0],&quot;469777928&quot;:[1]}">&nbsp;</span></p>
<ol>
<li><span data-contrast="auto"> The Application may be used by adult</span><span data-contrast="auto">legal</span><span data-contrast="auto">persons who are graduates of the&nbsp;</span><span data-contrast="auto">Poznan</span><span data-contrast="auto">&nbsp;University of Technology.</span><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6}">&nbsp;</span></li>
<li><span data-contrast="auto"> The User may download the Application on their mobile device at any time. After downloading the Application, the User may install it on their mobile device. There are no fees for downloading or installing the Application.</span></li>
<li><span data-contrast="auto"> In</span><span data-contrast="auto">order to download, install and use the Application, the User should have access to the Internet. The Application can be downloaded, as appropriate for mobile device operating systems, from Google Play, iTunes, Windows Store by searching for the name of the Application that the User is interested</span><span data-contrast="auto">.</span></li>
<li><span data-contrast="auto"> The minimum hardware requirements and types of mobile devices adapted to the Application are as follows:</span></li>
<li><span data-contrast="auto">a) The application can be downloaded to mobile devices with Internet access and operating on the basis of operating systems: Android, iOS or Windows, such as mobile phones, smartphones, palmtops or tablets;</span></li>
<li><span data-contrast="auto">b) The minimum requirements for access to the Internet are 2Mbit / s Internet bandwidth;</span></li>
<li><span data-contrast="auto">c) The minimum requirements for the operating system are Android version 4.2 API 17, iOS 9.0, Windows 10 Build 14393.</span></li>
<li><span data-contrast="auto"> The Administrator may publish Application updates. For the proper operation of the Application and use of all its functions, it is necessary to regularly update the Application. The change consisting in updating the Application is considered accepted no later than at the time of downloading this update to the User\'s mobile device.<br /><br /></span></li>
</ol>
<p><span data-ccp-props="{&quot;335551550&quot;:2,&quot;335551620&quot;:2,&quot;469777462&quot;:[1200],&quot;469777927&quot;:[0],&quot;469777928&quot;:[1]}">&nbsp;<strong><span data-contrast="auto">&sect;3&nbsp;</span></strong><strong><span data-contrast="auto">FUNCTIONALITY OF THE APPLICATION</span></strong><span data-ccp-props="{&quot;335551550&quot;:2,&quot;335551620&quot;:2,&quot;469777462&quot;:[1200],&quot;469777927&quot;:[0],&quot;469777928&quot;:[1]}">&nbsp;</span></span></p>
<ol>
<li><span data-contrast="auto"> After downloading and installing the Application, the User may:</span></li>
</ol>
<ul>
<li data-leveltext="-" data-font="Times New Roman" data-listid="2" data-aria-posinset="0" data-aria-level="1"><span data-contrast="auto">Create your account,</span><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;335559685&quot;:0,&quot;335559731&quot;:0,&quot;469777462&quot;:[1200],&quot;469777927&quot;:[0],&quot;469777928&quot;:[1]}">&nbsp;</span></li>
<li data-leveltext="-" data-font="Times New Roman" data-listid="2" data-aria-posinset="0" data-aria-level="1"><span data-contrast="auto">Modify the data saved in the account,</span><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;335559685&quot;:0,&quot;335559731&quot;:0,&quot;469777462&quot;:[1200],&quot;469777927&quot;:[0],&quot;469777928&quot;:[1]}">&nbsp;</span></li>
<li data-leveltext="-" data-font="Times New Roman" data-listid="2" data-aria-posinset="0" data-aria-level="1"><span data-contrast="auto">Create articles, events and gamification.</span><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;335559685&quot;:0,&quot;335559731&quot;:0,&quot;469777462&quot;:[1200],&quot;469777927&quot;:[0],&quot;469777928&quot;:[1]}">&nbsp;</span></li>
</ul>
<ol start="2">
<li><span data-contrast="auto"> The User may stop using the Application at any time. In order to remove the Application from the device, the User should uninstall the Application in accordance with the instructions of the given device.</span></li>
</ol>
<p><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;469777462&quot;:[1200],&quot;469777927&quot;:[0],&quot;469777928&quot;:[1]}">&nbsp;</span><strong><span data-contrast="auto"><strong><span data-contrast="auto">&sect;4</span></strong>&nbsp;</span></strong><strong><span data-contrast="auto">FINAL PROVISIONS</span></strong><span data-ccp-props="{&quot;335551550&quot;:2,&quot;335551620&quot;:2,&quot;469777462&quot;:[1200],&quot;469777927&quot;:[0],&quot;469777928&quot;:[1]}">&nbsp;</span></p>
<p><span data-ccp-props="{&quot;335551550&quot;:2,&quot;335551620&quot;:2,&quot;469777462&quot;:[1200],&quot;469777927&quot;:[0],&quot;469777928&quot;:[1]}">&nbsp;</span></p>
<ol>
<li><span data-contrast="auto"> The Administrator reserves the right to amend these Regulations at any time.</span></li>
<li><span data-contrast="auto"> The Administrator may withdraw access to the Application or its individual functionalities at any time.</span></li>
<li><span data-contrast="auto"> In</span><span data-contrast="auto">matters not covered by these Regulations, generally applicable law in</span><span data-contrast="auto">Poland</span><span data-contrast="auto">&nbsp;shall apply.</span><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;469777462&quot;:[1200],&quot;469777927&quot;:[0],&quot;469777928&quot;:[1]}">&nbsp;</span></li>
<li><span data-contrast="auto"> All complaints regarding the functioning of the Application will be considered within</span><br /><span data-contrast="auto">14 days from the date of their submission.</span><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;469777462&quot;:[1200],&quot;469777927&quot;:[0],&quot;469777928&quot;:[1]}">&nbsp;</span></li>
</ol>',
        ]);

        $this->insert('agreement_translation', [
            'agreement_id' => $personalDataProcessingId,
            'language_id' => $languagePlId,
            'content' => '<p><strong><span data-contrast="auto">POLITYKA PRYWATNOŚCI</span></strong><span data-ccp-props="{&quot;335551550&quot;:2,&quot;335551620&quot;:2}">&nbsp;</span></p>
<p><span data-ccp-props="{&quot;335551550&quot;:2,&quot;335551620&quot;:2}">&nbsp;</span></p>
<p><span data-contrast="auto">W myśl art. 13 Rozporządzenia Parlamentu Europejskiego i Rady (EU) 2016/679 z dnia&nbsp;</span>&nbsp;<br /><span data-contrast="auto">27 kwietnia 2016 roku w sprawie ochrony os&oacute;b fizycznych w związku z przetwarzaniem danych osobowych i w sprawie swobodnego przepływu takich danych oraz uchylenia dyrektywy 95/46/WE (zwane dalej: RODO) informujemy, że:</span><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6}">&nbsp;</span></p>
<ol>
<li><span data-contrast="auto"> Administratorem danych osobowych jest Politechnika Poznańska z siedzibą Pl. Marii Skłodowskiej &ndash; Curie 5, e-mail: biuro.rektora@put.poznan.pl, telefon: 61 665 3639.</span></li>
<li><span data-contrast="auto"> Dane kontaktowe Inspektora Ochrony Danych &ndash; Piotr Otomański,</span><a href="mailto:iod@put.poznan.pl"><span data-contrast="none"><span data-ccp-charstyle="Hyperlink">iod@put.poznan.pl</span></span></a></li>
<li><span data-contrast="auto"> Podstawą prawną przetwarzania danych osobowych jest dobrowolna zgoda &ndash; art. 6 ust. 1 lit. a RODO.&nbsp;</span></li>
<li><span data-contrast="auto"> Dane osobowe będą przetwarzane w celu założenia konta w Aplikacji powstałej</span><br /><span data-contrast="auto">w projekcie NAWA pt.&nbsp;</span><span data-contrast="auto">&bdquo;Pozostań w kontakcie z absolwentami PP,&nbsp;Stay&nbsp;connected&nbsp;with PUT Alumni&rdquo;</span><span data-contrast="auto">&nbsp;mającej na celu integrację środowiska absolwent&oacute;w Politechniki Poznańskiej.&nbsp;</span><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6}">&nbsp;</span></li>
<li><span data-contrast="auto"> Posiadają Państwo prawo dostępu do treści swoich danych, prawo ich sprostowania, usunięcia, a jeśli ma to zastosowanie prawo do przenoszenia danych oraz ograniczenia przetwarzania.</span></li>
<li><span data-contrast="auto"> Absolwentom, kt&oacute;rzy w związku z Aplikacją udostępnili Administratorowi swoje dane osobowe, w każdej chwili przysługuje prawo wniesienia sprzeciwu wobec ich przetwarzania</span><br /><span data-contrast="auto">z przyczyn związanych z ich szczeg&oacute;lną sytuacją, a także prawo wniesienia sprzeciwu na ich przetwarzanie.</span><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6}">&nbsp;</span></li>
<li><span data-contrast="auto"> Absolwentom, kt&oacute;rzy w związku z Aplikacją udostępnili Administratorowi swoje Dane Osobowe, w każdej chwili przysługuje prawo wycofania zgody na ich przetwarzanie.</span></li>
<li><span data-contrast="auto"> Aby skorzystać z kt&oacute;regokolwiek z uprawnień wskazanych w punktach 5-7 wystarczy,</span><br /><span data-contrast="auto">że Absolwent złoży stosowne żądanie Inspektorowi Ochrony Danych pisemnie lub na adres&nbsp;</span>&nbsp;<br /><span data-contrast="auto">e-mail:&nbsp;</span><a href="mailto:iod@put.poznan.pl"><span data-contrast="none"><span data-ccp-charstyle="Hyperlink">iod@put.poznan.pl</span></span></a><span data-contrast="auto">&nbsp;Administrator wykonuje żądanie klienta niezwłocznie&nbsp;</span>&nbsp;<br /><span data-contrast="auto">po weryfikacji zgłoszenia i osoby, od kt&oacute;rej żądanie pochodzi.</span><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6}">&nbsp;</span></li>
<li><span data-contrast="auto"> Mają Państwo prawo wniesienia skargi do Organu Nadzorczego, gdy uznają Państwo,</span><br /><span data-contrast="auto">iż przetwarzanie danych osobowych Państwa dotyczących narusza przepisy og&oacute;lnego rozporządzenia o ochronie danych osobowych z dnia 27 kwietnia 2016 r (RODO).&nbsp;</span><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6}">&nbsp;</span></li>
<li><span data-contrast="auto"> Podanie przez Państwa danych osobowych jest</span><span data-contrast="auto">dobrowolne, ale niezbędne do udziału we wszystkich</span><span data-contrast="auto">funkcjonalnościach</span><span data-contrast="auto">&nbsp;Aplikacji. Konsekwencją niepodania</span><span data-contrast="auto">&nbsp;danych osobowych będzie brak możliwości korzystania z Aplikacji i wzięcia udziału w projekcie.</span><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6}">&nbsp;</span></li>
<li><span data-contrast="auto"> Państwa dane nie będą przetwarzane w spos&oacute;b zautomatyzowany, w tym r&oacute;wnież</span><br /><span data-contrast="auto">w formie profilowania.&nbsp;</span><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6}">&nbsp;</span></li>
<li><span data-contrast="auto"> Usunięcie, ograniczenie, przeniesienie, zgłoszenie sprzeciwu względem przetwarzania Danych Osobowych lub wycofanie udzielonych zg&oacute;d przez posiadacza Aplikacji powodować będzie anulowanie dostępu konta, czego skutkiem będzie uniemożliwienie temu Absolwentowi korzystania z całodobowego i bezobsługowego dostępu do Aplikacji.</span></li>
<li><span data-contrast="auto"> Dane Osobowe Posiadacza Aplikacji będą przetwarzane przez okres nie dłuższy niż jest</span><br /><span data-contrast="auto">to niezbędne. Po tym czasie dane będą przechowywane jedynie na potrzeby zabezpieczenia roszczeń, wykonania obowiązk&oacute;w wynikających z obowiązujących przepis&oacute;w prawa m.in. podatkowych, rachunkowych, dla cel&oacute;w statystycznych i archiwizacyjnych. W każdym czasie można żądać ich usunięcia przez Administratora.</span><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6}">&nbsp;</span></li>
<li><span data-contrast="auto"> Dane osobowe Posiadacza Aplikacji mogą zostać usunięte w przypadku, gdy:</span></li>
</ol>
<ul>
<li data-leveltext="-" data-font="Verdana" data-listid="2" data-aria-posinset="0" data-aria-level="1"><span data-contrast="auto">dane osobowe nie są już niezbędne do cel&oacute;w, w kt&oacute;rych zostały zebrane lub w inny spos&oacute;b przetwarzane;</span><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;335559685&quot;:284,&quot;335559991&quot;:284,&quot;469777462&quot;:[1080,284],&quot;469777927&quot;:[0,0],&quot;469777928&quot;:[0,8]}">&nbsp;</span></li>
<li data-leveltext="-" data-font="Verdana" data-listid="2" data-aria-posinset="0" data-aria-level="1"><span data-contrast="auto">posiadacz Aplikacji cofnął zgodę, na kt&oacute;rej opiera się przetwarzanie i nie ma innej podstawy prawnej przetwarzania;</span><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;335559685&quot;:284,&quot;335559991&quot;:284,&quot;469777462&quot;:[1080,284],&quot;469777927&quot;:[0,0],&quot;469777928&quot;:[0,8]}">&nbsp;</span></li>
</ul>
<ul>
<li data-leveltext="-" data-font="Verdana" data-listid="2" data-aria-posinset="0" data-aria-level="1"><span data-contrast="auto">posiadacz Aplikacji wni&oacute;sł sprzeciw na mocy art. 21 ust 1 RODO wobec przetwarzania&nbsp;</span>&nbsp;<br /><span data-contrast="auto">i nie występują nadrzędne prawnie uzasadnione podstawy przetwarzania jego danych przez Administratora, lub posiadacz wni&oacute;sł sprzeciw na mocy art. 21 ust 2 RODO wobec przetwarzania;</span><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;335559685&quot;:284,&quot;335559991&quot;:284,&quot;469777462&quot;:[1080,284],&quot;469777927&quot;:[0,0],&quot;469777928&quot;:[0,8]}">&nbsp;</span></li>
<li data-leveltext="-" data-font="Verdana" data-listid="2" data-aria-posinset="0" data-aria-level="1"><span data-contrast="auto">dane osobowe posiadacza Aplikacji były przetwarzane niezgodnie z prawem;</span><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;335559685&quot;:284,&quot;335559991&quot;:284,&quot;469777462&quot;:[1080,284],&quot;469777927&quot;:[0,0],&quot;469777928&quot;:[0,8]}">&nbsp;</span></li>
<li data-leveltext="-" data-font="Verdana" data-listid="2" data-aria-posinset="0" data-aria-level="1"><span data-contrast="auto">dane osobowe posiadacza Aplikacji muszą zostać usunięte w celu wywiązania&nbsp;</span>&nbsp;<br /><span data-contrast="auto">się z obowiązku prawnego przewidzianego w prawie Unii Europejskiej lub prawie państwa członkowskiego, kt&oacute;remu podlega Administrator.</span><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;335559685&quot;:284,&quot;335559991&quot;:284,&quot;469777462&quot;:[1080,284],&quot;469777927&quot;:[0,0],&quot;469777928&quot;:[0,8]}">&nbsp;</span></li>
</ul>
<ol start="15">
<li><span data-contrast="auto"> Użytkownik samdecyduje,czy chce pobrać aktualizację Aplikacji poprzez ustawienia&nbsp;</span>&nbsp;<br /><span data-contrast="auto">w swoim urządzeniu. Automatyczne pobieranie aktualizacji uzależnione jest od ustawień osobistych urządzenia. Jeśli użytkownik nie chce, aby aktualizacje pobierały się automatycznie, powinien wyłączyć możliwość automatycznych aktualizacji w swoim urządzeniu.</span><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6}">&nbsp;</span></li>
</ol>',
        ]);

        $this->insert('agreement_translation', [
            'agreement_id' => $personalDataProcessingId,
            'language_id' => $languageEnId,
            'content' => '<p><strong><span data-contrast="auto">PRIVACY POLICY</span></strong><span data-ccp-props="{&quot;335551550&quot;:2,&quot;335551620&quot;:2,&quot;469777462&quot;:[1200],&quot;469777927&quot;:[0],&quot;469777928&quot;:[1]}">&nbsp;</span></p>
<p><span data-ccp-props="{&quot;335551550&quot;:2,&quot;335551620&quot;:2,&quot;469777462&quot;:[1200],&quot;469777927&quot;:[0],&quot;469777928&quot;:[1]}">&nbsp;</span></p>
<p><span data-contrast="auto">According to art. 13 of Regulation (EU) 2016/679 of the European Parliament and of the Council of 27 April 2016 on the protection of individuals with regard to the processing&nbsp;</span>&nbsp;<br /><span data-contrast="auto">of personal data and on the free movement of such data, and repealing Directive 95/46 / EC (hereinafter: the GDPR), we inform that:</span><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;469777462&quot;:[1200],&quot;469777927&quot;:[0],&quot;469777928&quot;:[1]}">&nbsp;</span></p>
<ol>
<li><span data-contrast="auto"> The administrator of personal data is Poznan University of Technology</span><span data-contrast="auto">,</span><span data-contrast="auto">Pl. MariaSkłodowska&nbsp;- Curie 5, e-mail: biuro.rektora@put.poznan.pl, phone: 61 665 3639.</span><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;469777462&quot;:[1200],&quot;469777927&quot;:[0],&quot;469777928&quot;:[1]}">&nbsp;</span></li>
<li><span data-contrast="auto"> Contact details of the Data Protection Inspector - PiotrOtomański,</span><a href="mailto:iod@put.poznan.pl"><span data-contrast="none"><span data-ccp-charstyle="Hyperlink">iod@put.poznan.pl</span></span></a><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;469777462&quot;:[1200],&quot;469777927&quot;:[0],&quot;469777928&quot;:[1]}">&nbsp;</span></li>
<li><span data-contrast="auto"> The legal basis for the processing of personal dat</span><span data-contrast="auto">a is voluntary consent -</span><span data-contrast="auto">&sect;</span><span data-contrast="auto">6(1)</span><span data-contrast="auto">&nbsp;and GDPR.</span><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;469777462&quot;:[1200],&quot;469777927&quot;:[0],&quot;469777928&quot;:[1]}">&nbsp;</span></li>
<li><span data-contrast="auto"> Personal data will be processed in order to set up an account in the Application created</span><br /><span data-contrast="auto">in the NAWA project entitled "</span><span data-contrast="auto">&nbsp;</span><span data-contrast="auto">Pozostań&nbsp;w&nbsp;kontakcie&nbsp;z&nbsp;absolwentami&nbsp;PP</span><span data-contrast="auto">, Stay connected with PUT Alumni" aimed at integrating the environment of graduates of the Poznan University of Technology.</span><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;469777462&quot;:[1200],&quot;469777927&quot;:[0],&quot;469777928&quot;:[1]}">&nbsp;</span></li>
<li><span data-contrast="auto"> You have the right to access your data, the right to rectify it, delete it and, if applicable,</span><br /><span data-contrast="auto">the right to transfer data and limit processing.</span><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;469777462&quot;:[1200],&quot;469777927&quot;:[0],&quot;469777928&quot;:[1]}">&nbsp;</span></li>
<li><span data-contrast="auto"> Graduates who, in connection with the Application, provided the Administrator with their personal data, have the right to object to their processing at any time for reasons related</span><br /><span data-contrast="auto">to their particular situation, as well as the right to object to their processing.</span><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;469777462&quot;:[1200],&quot;469777927&quot;:[0],&quot;469777928&quot;:[1]}">&nbsp;</span></li>
<li><span data-contrast="auto"> Graduates who, in connection with the Application, disclosed their Personal Data to the Administrator, have the right to withdraw their consent for their processing at any time.</span></li>
<li><span data-contrast="auto"> To exercise any of the rights indicated in points 5-7, it is sufficient for the Graduate</span><br /><span data-contrast="auto">to submit a relevant request to the Data Protection Inspector in writing or to the e-mail address: iod@put.poznan.pl. The Administrator shall make the client\'s request immediately after verifying the notification and the person, from which the request comes.</span><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;469777462&quot;:[1200],&quot;469777927&quot;:[0],&quot;469777928&quot;:[1]}">&nbsp;</span></li>
<li><span data-contrast="auto"> You have the right to lodge a complaint to the Supervisory Body, if you consider that the processing of your personal data violates the provisions of the General Regulation on the protection of personal data of April 27, 2016 (GDPR).</span></li>
<li><span data-contrast="auto"> Providing your personal data is voluntary, but necessary to participate in all functionalities of the Application. The consequence of not providing personal data will be the inability to use the Application and participate in the project.</span></li>
<li><span data-contrast="auto"> Your data will not be processed in an automated manner, including in the form</span><br /><span data-contrast="auto">of profiling.</span><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;469777462&quot;:[1200],&quot;469777927&quot;:[0],&quot;469777928&quot;:[1]}">&nbsp;</span></li>
<li><span data-contrast="auto"> Removal, limitation, transfer, objection to the processing of Personal Data or withdrawal of consents granted by the Application holder will result in the account being canceled, which will result in this graduate being prevented from using 24-hour and unattended access to the Application.</span></li>
<li><span data-contrast="auto"> The Application Holder\'s Personal Data will be processed for a period not longer than necessary. After this time, the data will be stored only for the purposes of securing claims, performance of obligations arising from applicable law, including tax, accounting,</span><br /><span data-contrast="auto">for statistical and archiving purposes. You can request their removal by the Administrator&nbsp;</span>&nbsp;<br /><span data-contrast="auto">at any time.</span><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;469777462&quot;:[1200],&quot;469777927&quot;:[0],&quot;469777928&quot;:[1]}">&nbsp;</span></li>
<li><span data-contrast="auto"> The Application Holder\'s personal data may be deleted if:</span></li>
</ol>
<ul>
<li data-leveltext="-" data-font="Times New Roman" data-listid="2" data-aria-posinset="0" data-aria-level="1"><span data-contrast="auto">personal data are no longer necessary for the purposes for which they were collected&nbsp;</span>&nbsp;<br /><span data-contrast="auto">or otherwise processed;</span><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;335559685&quot;:0,&quot;335559731&quot;:0,&quot;469777462&quot;:[720,284,1200],&quot;469777927&quot;:[0,0,0],&quot;469777928&quot;:[0,8,1]}">&nbsp;</span></li>
<li data-leveltext="-" data-font="Times New Roman" data-listid="2" data-aria-posinset="0" data-aria-level="1"><span data-contrast="auto">the Application holder withdrew the consent on which the processing is based and there&nbsp;</span>&nbsp;<br /><span data-contrast="auto">is no other legal basis for the processing;</span><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;335559685&quot;:0,&quot;335559731&quot;:0,&quot;469777462&quot;:[720,284,1200],&quot;469777927&quot;:[0,0,0],&quot;469777928&quot;:[0,8,1]}">&nbsp;</span></li>
<li data-leveltext="-" data-font="Times New Roman" data-listid="2" data-aria-posinset="0" data-aria-level="1"><span data-contrast="auto">the Application holder raised an objection pursuant to art. 21</span><span data-contrast="auto">(</span><span data-contrast="auto">1</span><span data-contrast="auto">)</span><span data-contrast="auto">&nbsp;of the GDPR regarding processing and there are no overriding legitimate grounds for the processing of his data by the Administrator, or the holder has raised an objection pursuant to art. 21</span><span data-contrast="auto">(</span><span data-contrast="auto">2</span><span data-contrast="auto">)</span><span data-contrast="auto">&nbsp;of the GDPR towards processing;</span><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;335559685&quot;:0,&quot;335559731&quot;:0,&quot;469777462&quot;:[720,284,1200],&quot;469777927&quot;:[0,0,0],&quot;469777928&quot;:[0,8,1]}">&nbsp;</span></li>
<li data-leveltext="-" data-font="Times New Roman" data-listid="2" data-aria-posinset="0" data-aria-level="1"><span data-contrast="auto">personal data of the Application holder was processed unlawfully;</span><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;335559685&quot;:0,&quot;335559731&quot;:0,&quot;469777462&quot;:[720,284,1200],&quot;469777927&quot;:[0,0,0],&quot;469777928&quot;:[0,8,1]}">&nbsp;</span></li>
<li data-leveltext="-" data-font="Times New Roman" data-listid="2" data-aria-posinset="0" data-aria-level="1"><span data-contrast="auto">the personal data of the Application holder must be removed in order to comply with the legal obligation provided for in European Union law or the law of the&nbsp;</span><span data-contrast="auto">Member</span><span data-contrast="auto">&nbsp;</span><span data-contrast="auto">State</span><span data-contrast="auto">&nbsp;to which the Administrator is subject.</span><span data-ccp-props="{&quot;335551550&quot;:6,&quot;335551620&quot;:6,&quot;335559685&quot;:0,&quot;335559731&quot;:0,&quot;469777462&quot;:[720,284,1200],&quot;469777927&quot;:[0,0,0],&quot;469777928&quot;:[0,8,1]}">&nbsp;</span></li>
</ul>
<ol start="15">
<li><span data-contrast="auto"> The user decides whether wants to download the Application update through the settings on his device. Automatic download of updates depends on the personal settings of the device. If you do not want the updates to download automatically, you should turn off automatic updates on your device.</span></li>
</ol>',
        ]);
    }

    public function safeDown() {
        $this->delete('agreement_translation');
    }
}
