<?php

return [
    [
        'id' => 1,
        'event_type_id' => 1,
        'title' => 'Visit 1',
        'date_start' => '2019-06-03 08:00:00',
        'date_end' => '2019-06-03 09:00:00',
        'location' => 1,
        'user_author_id' => 1,
        'user_assigned_id' => null,
        'user_patient_id' => 2,
        'is_active' => 1,
    ],
    [
        'id' => 2,
        'event_type_id' => 4,
        'title' => 'Training 1',
        'date_start' => '2019-06-10 11:30:00',
        'date_end' => '2019-06-10 12:15:00',
        'location' => null,
        'user_author_id' => 3,
        'user_assigned_id' => 3,
        'user_patient_id' => 2,
        'is_active' => 1,
    ],
    [
        'id' => 3,
        'event_type_id' => 1,
        'title' => 'Not Active Visit',
        'date_start' => '2019-06-11 13:00:00',
        'date_end' => '2019-06-11 13:30:00',
        'location' => null,
        'user_author_id' => 1,
        'user_assigned_id' => null,
        'user_patient_id' => 2,
        'is_active' => 0,
    ],
    [
        'id' => 4,
        'event_type_id' => 2,
        'title' => 'Task 1',
        'date_start' => '2019-05-15 14:00:00',
        'date_end' => '2019-05-15 15:00:00',
        'location' => 2,
        'user_author_id' => 1,
        'user_assigned_id' => 2,
        'user_patient_id' => 2,
        'is_active' => 1,
    ],
    [
        'id' => 5,
        'event_type_id' => 3,
        'title' => 'Break 1',
        'date_start' => '2019-08-20 08:00:00',
        'date_end' => '2019-08-20 08:10:00',
        'location' => null,
        'user_author_id' => 1,
        'user_assigned_id' => null,
        'user_patient_id' => 2,
        'is_active' => 1,
    ],
    // [
    //     'id' => 6,
    //     'event_type_id' => 1,
    //     'title' => 'Visit y',
    //     'date_start' => '2021-07-03 8:00:00',
    //     'date_end' => '2021-07-03 9:00:00',
    //     'location' => 1,
    //     'user_author_id' => 1,
    //     'user_assigned_id' => null,
    //     'user_patient_id' => 2,
    //     'is_active' => 1,
    // ],
    // [
    //     'id' => 7,
    //     'event_type_id' => 1,
    //     'title' => 'Visit x',
    //     'date_start' => '2021-07-03 11:00:00',
    //     'date_end' => '2021-07-03 12:00:00',
    //     'location' => 1,
    //     'user_author_id' => 1,
    //     'user_assigned_id' => null,
    //     'user_patient_id' => 2,
    //     'is_active' => 1,
    // ],
    [
        'id' => 6,
        'event_type_id' => 1,
        'title' => 'Without Date Visit',
        'date_start' => null,
        'date_end' => null,
        'location' => 1,
        'user_author_id' => 1,
        'user_assigned_id' => null,
        'user_patient_id' => 2,
        'is_active' => 1,
    ],
];